// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/_middleware.ts";
import * as $3 from "./routes/api/login.ts";
import * as $4 from "./routes/api/signup.ts";
import * as $5 from "./routes/contacts.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/login.tsx";
import * as $8 from "./routes/profile.tsx";
import * as $9 from "./routes/role/[id].tsx";
import * as $10 from "./routes/role/[id]/edit.tsx";
import * as $11 from "./routes/role/[id]/note/add.tsx";
import * as $12 from "./routes/role/[id]/notes.tsx";
import * as $13 from "./routes/role/add.tsx";
import * as $14 from "./routes/roles.tsx";
import * as $15 from "./routes/signout.ts";
import * as $16 from "./routes/signup.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/_middleware.ts": $2,
    "./routes/api/login.ts": $3,
    "./routes/api/signup.ts": $4,
    "./routes/contacts.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/login.tsx": $7,
    "./routes/profile.tsx": $8,
    "./routes/role/[id].tsx": $9,
    "./routes/role/[id]/edit.tsx": $10,
    "./routes/role/[id]/note/add.tsx": $11,
    "./routes/role/[id]/notes.tsx": $12,
    "./routes/role/add.tsx": $13,
    "./routes/roles.tsx": $14,
    "./routes/signout.ts": $15,
    "./routes/signup.tsx": $16,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
